name: dev-workflow
on: push
jobs:
  prod-workflow:
    name: Get machine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: dotnet build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with: 
          name: dev
          path: /home/runner/work/workflow/workflow/workflow/obj/Debug/netcoreapp3.1
        
    
