name: prod-workflow
on: push
jobs:
  prod-workflow:
    name: Get machine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: dotnet build
      - name: Publish project
        run: dotnet publish --configuration Release --output /home/runner/work/workflow/workflow/workflow/publish
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with: 
          name: prod
          path: /home/runner/work/workflow/workflow/workflow/publish
        
    
